import Navbar from './components/Navbar'
import './globals.css'
import { Mulish } from 'next/font/google'

const mulish = Mulish({ 
  
  subsets: ['latin'] ,
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={mulish.className}>
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
